"""Remove incorrect token relationship from TodooDB

Revision ID: 0975b444f352
Revises: ad0b13e0f8d6
Create Date: 2026-01-17 14:31:04.075528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0975b444f352'
down_revision: Union[str, Sequence[str], None] = 'ad0b13e0f8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
