"""make is_active

Revision ID: 39c0bd3649fe
Revises: 8c0b95c271a8
Create Date: 2026-02-14 18:15:08.994363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c0bd3649fe'
down_revision: Union[str, Sequence[str], None] = '8c0b95c271a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'is_active')
    # ### end Alembic commands ###
