"""remove_access_token_field

Revision ID: 56cf9612708e
Revises: 0975b444f352
Create Date: 2026-01-31 15:48:24.417269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56cf9612708e'
down_revision: Union[str, Sequence[str], None] = '0975b444f352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('access_token', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
