"""Create all tables

Revision ID: 5d7ade5d212a
Revises: 
Create Date: 2026-01-14 19:24:14.051004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d7ade5d212a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todoofinished', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='время  устанавливается в ендпоинте(по логике такой всего 1)',
               existing_comment='время  автоматически устанавливается при создании записи',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('todoofinished', 'all_time_cost',
               existing_type=sa.INTEGER(),
               comment='общее время затраченое на задачу в секундах вычисляется при переходе в TodooFinished',
               existing_comment='общее время затраченое на задачу вычисляется при каждом запросе',
               existing_nullable=True)
    op.drop_column('todoofinished', 'work_time_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todoofinished', sa.Column('work_time_cost', postgresql.INTERVAL(), autoincrement=False, nullable=True, comment='рабочее время затраченое на задачу высчитывается при каждом запросе (считает только рабочие часы)'))
    op.alter_column('todoofinished', 'all_time_cost',
               existing_type=sa.INTEGER(),
               comment='общее время затраченое на задачу вычисляется при каждом запросе',
               existing_comment='общее время затраченое на задачу в секундах вычисляется при переходе в TodooFinished',
               existing_nullable=True)
    op.alter_column('todoofinished', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='время  автоматически устанавливается при создании записи',
               existing_comment='время  устанавливается в ендпоинте(по логике такой всего 1)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
