"""set user_id not null

Revision ID: 74a2ddfb20d4
Revises: 39c0bd3649fe
Create Date: 2026-02-18 19:57:48.804409

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74a2ddfb20d4"
down_revision: Union[str, Sequence[str], None] = "39c0bd3649fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("todoofinished", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("todoofinished", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
