"""delete_is_active

Revision ID: 8c0b95c271a8
Revises: 977be88b1c3a
Create Date: 2026-02-14 18:14:30.843235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c0b95c271a8"
down_revision: Union[str, Sequence[str], None] = "977be88b1c3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tokens", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tokens", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
