"""add comment to TodooDB and TodooFinished

Revision ID: a747478e4a46
Revises: 74a2ddfb20d4
Create Date: 2026-02-21 14:05:19.657464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a747478e4a46'
down_revision: Union[str, Sequence[str], None] = '74a2ddfb20d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todoo', sa.Column('comment', sa.String(length=500), nullable=True))
    op.add_column('todoofinished', sa.Column('comment', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todoofinished', 'comment')
    op.drop_column('todoo', 'comment')
    # ### end Alembic commands ###
